In [1]:
path1 = r"C:\Users\UNegi\OneDrive - Cognitio Analytics LLC\makethon\icd_10_cms_super_grouper.xlsx"
path2 = r"C:\Users\UNegi\OneDrive - Cognitio Analytics LLC\makethon\chapter_and_section.xlsx"

In [4]:
import pandas as pd
df = pd.read_excel(path1)
df.rename(columns={'Code_Super_Grouper':'Code_Grouper','Super_Grouper_description':'Grouper_description'},inplace=True)

In [5]:
df

,Code,Description,Code_Grouper,Grouper_description
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...",A00,Cholera
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor",A00,Cholera
2,A009,"Cholera, unspecified",A00,Cholera
3,A0100,"Typhoid fever, unspecified",A01,Typhoid and paratyphoid fevers
4,A0101,Typhoid meningitis,A01,Typhoid and paratyphoid fevers
...,...,...,...,...
74714,Z9981,Dependence on supplemental oxygen,Z99,"Dependence on enabling machines and devices, n..."
74715,Z9989,Dependence on other enabling machines and devices,Z99,"Dependence on enabling machines and devices, n..."
74716,U070,Vaping-related disorder,U07,Emergency use of U07
74717,U071,COVID-19,U07,Emergency use of U07
74718,U099,"Post COVID-19 condition, unspecified",U09,NaN

In [6]:
excel_file = pd.ExcelFile(path2)

# Get all sheet names
print(excel_file.sheet_names)

['Section', 'Chapter']

In [8]:
df_sec = pd.read_excel(path2,sheet_name='Section')

In [12]:
df_chap = pd.read_excel(path2,sheet_name='Chapter')

In [13]:
df_chap

             Chapter                                       Chapter_Name
0   Chapter I00-I99                  Diseases of the circulatory system
1   Chapter Z00-Z99    Factors influencing health status and contact...
2   Chapter O00-O9A            Pregnancy, childbirth and the puerperium
3   Chapter V00-Y99                        External causes of morbidity
4   Chapter U00-U85                          Codes for special purposes
5   Chapter S00-T88    Injury, poisoning and certain other consequen...
6   Chapter H60-H95             Diseases of the ear and mastoid process
7   Chapter A00-B99           Certain infectious and parasitic diseases
8   Chapter M00-M99    Diseases of the musculoskeletal system and co...
9   Chapter K00-K95                    Diseases of the digestive system
10  Chapter J00-J99                  Diseases of the respiratory system
11  Chapter P00-P96    Certain conditions originating in the perinat...
12  Chapter F01-F99    Mental, Behavioral and Neurodevelopmental dis...
13  Chapter C00-D49                                           Neoplasms
14  Chapter H00-H59                      Diseases of the eye and adnexa
15  Chapter L00-L99        Diseases of the skin and subcutaneous tissue
16   Chapter D50-D89  Diseases of the blood and blood forming organs...
17  Chapter R00-R99    Symptoms, signs and abnormal clinical and lab...
18  Chapter Q00-Q99    Congenital malformations, deformations and ch...
19  Chapter N00-N99                Diseases of the genitourinary system
20  Chapter G00-G99                      Diseases of the nervous system
21  Chapter E00-E89       Endocrine, nutritional and metabolic diseases

In [9]:
df_sec

      Section                                       Section_Name
0    I95-I99    Other and unspecified disorders of the circul...
1    G30-G32    Other degenerative diseases of the nervous sy...
2    P80-P83    Conditions involving the integument and tempe...
3        O09                  Supervision of high risk pregnancy
4    Q20-Q28    Congenital malformations of the circulatory s...
..        ...                                                ...
220  M00-M25                                       Arthropathies
221   F20-F29  Schizophrenia, schizotypal, delusional, and ot...
222  S20-S29                              Injuries to the thorax
223  Y21-Y33                        Event of undetermined intent
224  O00-O08                     Pregnancy with abortive outcome

[225 rows x 2 columns]

In [10]:

import pandas as pd

# Sample data based on user description
datadf = df.copy()

df_sec = df_sec.copy()

# Function to check if a code falls in a section range or matches single code
def match_section(code_grouper, section):
    if '-' in section:
        start, end = section.split('-')
        # Compare alphanumeric codes lexicographically
        return start <= code_grouper <= end
    else:
        return code_grouper == section

# For each row in datadf, find matching section
section_list = []
section_name_list = []

for cg in datadf['Code_Grouper']:
    matched_section = None
    matched_name = None
    for sec, name in zip(df_sec['Section'], df_sec['Section_Name']):
        if match_section(cg, sec):
            matched_section = sec
            matched_name = name
            break
    section_list.append(matched_section)
    section_name_list.append(matched_name)

# Add to datadf
datadf['Section'] = section_list
datadf['Section_Name'] = section_name_list

print(datadf)

           Code                                        Description  \
0          A000  Cholera due to Vibrio cholerae 01, biovar chol...
1      A001        Cholera due to Vibrio cholerae 01, biovar eltor
2      A009                                   Cholera, unspecified
3      A0100                            Typhoid fever, unspecified
4      A0101                                    Typhoid meningitis
...         ...                                                ...
74714  Z9981                     Dependence on supplemental oxygen
74715  Z9989     Dependence on other enabling machines and devices
74716  U070                                Vaping-related disorder
74717  U071                                               COVID-19
74718  U099                   Post COVID-19 condition, unspecified

      Code_Grouper                                Grouper_description  \
0              A00                                            Cholera
1              A00                                            Cholera
2              A00                                            Cholera
3              A01                     Typhoid and paratyphoid fevers
4              A01                     Typhoid and paratyphoid fevers
...            ...                                                ...
74714          Z99  Dependence on enabling machines and devices, n...
74715          Z99  Dependence on enabling machines and devices, n...
74716          U07                               Emergency use of U07
74717          U07                               Emergency use of U07
74718          U09                                                NaN

        Section                                       Section_Name
0      A00-A09                      Intestinal infectious diseases
1      A00-A09                      Intestinal infectious diseases
2      A00-A09                      Intestinal infectious diseases
3      A00-A09                      Intestinal infectious diseases
4      A00-A09                      Intestinal infectious diseases
...         ...                                                ...
74714  Z77-Z99    Persons with potential health hazards related...
74715  Z77-Z99    Persons with potential health hazards related...
74716  U00-U49    Provisional assignment of new diseases of unc...
74717  U00-U49    Provisional assignment of new diseases of unc...
74718  U00-U49    Provisional assignment of new diseases of unc...

[74719 rows x 6 columns]

In [11]:
datadf

,Code,Description,Code_Grouper,Grouper_description,Section,Section_Name
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...",A00,Cholera,A00-A09,Intestinal infectious diseases
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor",A00,Cholera,A00-A09,Intestinal infectious diseases
2,A009,"Cholera, unspecified",A00,Cholera,A00-A09,Intestinal infectious diseases
3,A0100,"Typhoid fever, unspecified",A01,Typhoid and paratyphoid fevers,A00-A09,Intestinal infectious diseases
4,A0101,Typhoid meningitis,A01,Typhoid and paratyphoid fevers,A00-A09,Intestinal infectious diseases
...,...,...,...,...,...,...
74714,Z9981,Dependence on supplemental oxygen,Z99,"Dependence on enabling machines and devices, n...",Z77-Z99,Persons with potential health hazards related...
74715,Z9989,Dependence on other enabling machines and devices,Z99,"Dependence on enabling machines and devices, n...",Z77-Z99,Persons with potential health hazards related...
74716,U070,Vaping-related disorder,U07,Emergency use of U07,U00-U49,Provisional assignment of new diseases of unc...
74717,U071,COVID-19,U07,Emergency use of U07,U00-U49,Provisional assignment of new diseases of unc...
74718,U099,"Post COVID-19 condition, unspecified",U09,NaN,U00-U49,Provisional assignment of new diseases of unc...

In [16]:
import pandas as pd

# ----- Step 1: Clean Section range -----
datadf[['sec_start', 'sec_end']] = datadf['Section'].str.split('-', expand=True)
datadf['sec_start'] = datadf['sec_start'].str.strip()
datadf['sec_end'] = datadf['sec_end'].str.strip()

# ----- Step 2: Extract chapter ranges -----
df_chap[['chapter_label', 'chapter_range']] = df_chap['Chapter'].str.split(' ', n=1, expand=True)
df_chap[['chap_start', 'chap_end']] = df_chap['chapter_range'].str.split('-', expand=True)
df_chap['chap_start'] = df_chap['chap_start'].str.strip()
df_chap['chap_end']   = df_chap['chap_end'].str.strip()

# ----- Helper: safely check if code is between start and end -----
def belongs_to_chapter(code, chap_start, chap_end):
    if pd.isna(code) or pd.isna(chap_start) or pd.isna(chap_end):
        return False
    return chap_start <= code <= chap_end  # works for ICD codes as strings

# ----- Step 3: Map chapter using sec_start -----
def map_chapter(row):
    code = row['sec_start']
    for _, chap in df_chap.iterrows():
        if belongs_to_chapter(code, chap['chap_start'], chap['chap_end']):
            return pd.Series([chap['Chapter'], chap['Chapter_Name']])
    return pd.Series([None, None])

datadf[['Chapter', 'Chapter_Name']] = datadf.apply(map_chapter, axis=1)

print(datadf)

           Code                                        Description  \
0          A000  Cholera due to Vibrio cholerae 01, biovar chol...
1      A001        Cholera due to Vibrio cholerae 01, biovar eltor
2      A009                                   Cholera, unspecified
3      A0100                            Typhoid fever, unspecified
4      A0101                                    Typhoid meningitis
...         ...                                                ...
74714  Z9981                     Dependence on supplemental oxygen
74715  Z9989     Dependence on other enabling machines and devices
74716  U070                                Vaping-related disorder
74717  U071                                               COVID-19
74718  U099                   Post COVID-19 condition, unspecified

      Code_Grouper                                Grouper_description  \
0              A00                                            Cholera
1              A00                                            Cholera
2              A00                                            Cholera
3              A01                     Typhoid and paratyphoid fevers
4              A01                     Typhoid and paratyphoid fevers
...            ...                                                ...
74714          Z99  Dependence on enabling machines and devices, n...
74715          Z99  Dependence on enabling machines and devices, n...
74716          U07                               Emergency use of U07
74717          U07                               Emergency use of U07
74718          U09                                                NaN

        Section                                       Section_Name sec_start  \
0      A00-A09                      Intestinal infectious diseases       A00
1      A00-A09                      Intestinal infectious diseases       A00
2      A00-A09                      Intestinal infectious diseases       A00
3      A00-A09                      Intestinal infectious diseases       A00
4      A00-A09                      Intestinal infectious diseases       A00
...         ...                                                ...       ...
74714  Z77-Z99    Persons with potential health hazards related...       Z77
74715  Z77-Z99    Persons with potential health hazards related...       Z77
74716  U00-U49    Provisional assignment of new diseases of unc...       U00
74717  U00-U49    Provisional assignment of new diseases of unc...       U00
74718  U00-U49    Provisional assignment of new diseases of unc...       U00

      sec_end           Chapter  \
0         A09  Chapter A00-B99
1         A09  Chapter A00-B99
2         A09  Chapter A00-B99
3         A09  Chapter A00-B99
4         A09  Chapter A00-B99
...       ...               ...
74714     Z99  Chapter Z00-Z99
74715     Z99  Chapter Z00-Z99
74716     U49  Chapter U00-U85
74717     U49  Chapter U00-U85
74718     U49  Chapter U00-U85

                                            Chapter_Name
0              Certain infectious and parasitic diseases
1              Certain infectious and parasitic diseases
2              Certain infectious and parasitic diseases
3              Certain infectious and parasitic diseases
4              Certain infectious and parasitic diseases
...                                                  ...
74714   Factors influencing health status and contact...
74715   Factors influencing health status and contact...
74716                         Codes for special purposes
74717                         Codes for special purposes
74718                         Codes for special purposes

[74719 rows x 10 columns]

In [ ]:
datadf.to_excel('ICD_10_CM_Complete_Data.xlsx')

: